# Auto-generated by IBM Bob PHI Compliance Scanner
# Generated: 2026-05-17 12:48:40
# Source: patient-api\app.py
# HIPAA Rules covered: §164.312(a)(1), §164.312(b), §164.312(d), §164.312(e)(1), §164.502(b)

import pytest
import re

# ── Helpers ──────────────────────────────────────────────────────────────────

SSN_PATTERN    = re.compile(r'\b\d{3}-\d{2}-\d{4}\b')
MRN_PATTERN    = re.compile(r'\bMRN-?\d{4,}\b', re.IGNORECASE)
EMAIL_PATTERN  = re.compile(r'[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}')
PHONE_PATTERN  = re.compile(r'\b\d{3}[-.]\d{3}[-.]\d{4}\b')

def contains_phi(text: str) -> bool:
    """Returns True if text contains any raw PHI."""
    t = str(text)
    return bool(
        SSN_PATTERN.search(t) or
        MRN_PATTERN.search(t) or
        EMAIL_PATTERN.search(t) or
        PHONE_PATTERN.search(t)
    )

# ── Tests ─────────────────────────────────────────────────────────────────────

class TestSsnLine25:
    """
    Compliance tests for patient-api\app.py:25
    Violation: Social Security Number
    HIPAA Rule: §164.312(a)(1)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.312(a)(1) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.312(a)(1)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestMrnLine27:
    """
    Compliance tests for patient-api\app.py:27
    Violation: Medical Record Number
    HIPAA Rule: §164.312(a)(1)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.312(a)(1) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.312(a)(1)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestSsnLine36:
    """
    Compliance tests for patient-api\app.py:36
    Violation: Social Security Number
    HIPAA Rule: §164.312(a)(1)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.312(a)(1) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.312(a)(1)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestMrnLine36:
    """
    Compliance tests for patient-api\app.py:36
    Violation: Medical Record Number
    HIPAA Rule: §164.312(a)(1)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.312(a)(1) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.312(a)(1)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestSsnLine37:
    """
    Compliance tests for patient-api\app.py:37
    Violation: Social Security Number
    HIPAA Rule: §164.312(a)(1)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.312(a)(1) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.312(a)(1)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestMrnLine37:
    """
    Compliance tests for patient-api\app.py:37
    Violation: Medical Record Number
    HIPAA Rule: §164.312(a)(1)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.312(a)(1) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.312(a)(1)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestSsnLine59:
    """
    Compliance tests for patient-api\app.py:59
    Violation: Social Security Number
    HIPAA Rule: §164.312(a)(1)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.312(a)(1) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.312(a)(1)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestLogphiLine59:
    """
    Compliance tests for patient-api\app.py:59
    Violation: PHI in log: Social Security Number
    HIPAA Rule: §164.312(b)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.312(b) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.312(b)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestSsnLine68:
    """
    Compliance tests for patient-api\app.py:68
    Violation: Social Security Number
    HIPAA Rule: §164.312(a)(1)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.312(a)(1) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.312(a)(1)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestMrnLine68:
    """
    Compliance tests for patient-api\app.py:68
    Violation: Medical Record Number
    HIPAA Rule: §164.312(a)(1)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.312(a)(1) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.312(a)(1)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestSsnLine69:
    """
    Compliance tests for patient-api\app.py:69
    Violation: Social Security Number
    HIPAA Rule: §164.312(a)(1)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.312(a)(1) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.312(a)(1)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestMrnLine69:
    """
    Compliance tests for patient-api\app.py:69
    Violation: Medical Record Number
    HIPAA Rule: §164.312(a)(1)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.312(a)(1) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.312(a)(1)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestSsnLine73:
    """
    Compliance tests for patient-api\app.py:73
    Violation: Social Security Number
    HIPAA Rule: §164.312(a)(1)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.312(a)(1) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.312(a)(1)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestLogphiLine73:
    """
    Compliance tests for patient-api\app.py:73
    Violation: PHI in log: Social Security Number
    HIPAA Rule: §164.312(b)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.312(b) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.312(b)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestSsnLine74:
    """
    Compliance tests for patient-api\app.py:74
    Violation: Social Security Number
    HIPAA Rule: §164.312(a)(1)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.312(a)(1) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.312(a)(1)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestNameLine24:
    """
    Compliance tests for patient-api\app.py:24
    Violation: Patient Name
    HIPAA Rule: §164.312(a)(1)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.312(a)(1) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.312(a)(1)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestDobLine26:
    """
    Compliance tests for patient-api\app.py:26
    Violation: Date of Birth
    HIPAA Rule: §164.312(a)(1)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.312(a)(1) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.312(a)(1)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestDiagnosisLine28:
    """
    Compliance tests for patient-api\app.py:28
    Violation: Diagnosis / ICD Code
    HIPAA Rule: §164.502(b)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.502(b) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.502(b)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestPhoneLine29:
    """
    Compliance tests for patient-api\app.py:29
    Violation: Phone Number
    HIPAA Rule: §164.312(a)(1)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.312(a)(1) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.312(a)(1)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestEmailLine30:
    """
    Compliance tests for patient-api\app.py:30
    Violation: Email Address
    HIPAA Rule: §164.312(a)(1)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.312(a)(1) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.312(a)(1)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestDobLine36:
    """
    Compliance tests for patient-api\app.py:36
    Violation: Date of Birth
    HIPAA Rule: §164.312(a)(1)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.312(a)(1) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.312(a)(1)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestPhoneLine36:
    """
    Compliance tests for patient-api\app.py:36
    Violation: Phone Number
    HIPAA Rule: §164.312(a)(1)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.312(a)(1) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.312(a)(1)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestEmailLine36:
    """
    Compliance tests for patient-api\app.py:36
    Violation: Email Address
    HIPAA Rule: §164.312(a)(1)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.312(a)(1) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.312(a)(1)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestNameLine36:
    """
    Compliance tests for patient-api\app.py:36
    Violation: Patient Name
    HIPAA Rule: §164.312(a)(1)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.312(a)(1) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.312(a)(1)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestDiagnosisLine36:
    """
    Compliance tests for patient-api\app.py:36
    Violation: Diagnosis / ICD Code
    HIPAA Rule: §164.502(b)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.502(b) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.502(b)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestDobLine37:
    """
    Compliance tests for patient-api\app.py:37
    Violation: Date of Birth
    HIPAA Rule: §164.312(a)(1)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.312(a)(1) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.312(a)(1)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestEmailLine37:
    """
    Compliance tests for patient-api\app.py:37
    Violation: Email Address
    HIPAA Rule: §164.312(a)(1)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.312(a)(1) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.312(a)(1)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestMissingauthLine42:
    """
    Compliance tests for patient-api\app.py:42
    Violation: Endpoint missing authentication
    HIPAA Rule: §164.312(d)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.312(d) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.312(d)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestMissingauthLine51:
    """
    Compliance tests for patient-api\app.py:51
    Violation: Endpoint missing authentication
    HIPAA Rule: §164.312(d)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.312(d) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.312(d)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestNameLine59:
    """
    Compliance tests for patient-api\app.py:59
    Violation: Patient Name
    HIPAA Rule: §164.312(a)(1)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.312(a)(1) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.312(a)(1)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestMissingauthLine62:
    """
    Compliance tests for patient-api\app.py:62
    Violation: Endpoint missing authentication
    HIPAA Rule: §164.312(d)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.312(d) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.312(d)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestDobLine68:
    """
    Compliance tests for patient-api\app.py:68
    Violation: Date of Birth
    HIPAA Rule: §164.312(a)(1)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.312(a)(1) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.312(a)(1)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestPhoneLine68:
    """
    Compliance tests for patient-api\app.py:68
    Violation: Phone Number
    HIPAA Rule: §164.312(a)(1)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.312(a)(1) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.312(a)(1)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestEmailLine68:
    """
    Compliance tests for patient-api\app.py:68
    Violation: Email Address
    HIPAA Rule: §164.312(a)(1)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.312(a)(1) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.312(a)(1)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestNameLine68:
    """
    Compliance tests for patient-api\app.py:68
    Violation: Patient Name
    HIPAA Rule: §164.312(a)(1)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.312(a)(1) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.312(a)(1)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestDiagnosisLine68:
    """
    Compliance tests for patient-api\app.py:68
    Violation: Diagnosis / ICD Code
    HIPAA Rule: §164.502(b)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.502(b) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.502(b)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestDobLine69:
    """
    Compliance tests for patient-api\app.py:69
    Violation: Date of Birth
    HIPAA Rule: §164.312(a)(1)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.312(a)(1) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.312(a)(1)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestPhoneLine69:
    """
    Compliance tests for patient-api\app.py:69
    Violation: Phone Number
    HIPAA Rule: §164.312(a)(1)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.312(a)(1) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.312(a)(1)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestEmailLine69:
    """
    Compliance tests for patient-api\app.py:69
    Violation: Email Address
    HIPAA Rule: §164.312(a)(1)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.312(a)(1) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.312(a)(1)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestNameLine69:
    """
    Compliance tests for patient-api\app.py:69
    Violation: Patient Name
    HIPAA Rule: §164.312(a)(1)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.312(a)(1) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.312(a)(1)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestDiagnosisLine69:
    """
    Compliance tests for patient-api\app.py:69
    Violation: Diagnosis / ICD Code
    HIPAA Rule: §164.502(b)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.502(b) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.502(b)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestNameLine73:
    """
    Compliance tests for patient-api\app.py:73
    Violation: Patient Name
    HIPAA Rule: §164.312(a)(1)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.312(a)(1) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.312(a)(1)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestAddressLine31:
    """
    Compliance tests for patient-api\app.py:31
    Violation: Street Address
    HIPAA Rule: §164.312(a)(1)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.312(a)(1) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.312(a)(1)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestAddressLine36:
    """
    Compliance tests for patient-api\app.py:36
    Violation: Street Address
    HIPAA Rule: §164.312(a)(1)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.312(a)(1) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.312(a)(1)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestAddressLine37:
    """
    Compliance tests for patient-api\app.py:37
    Violation: Street Address
    HIPAA Rule: §164.312(a)(1)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.312(a)(1) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.312(a)(1)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestAddressLine68:
    """
    Compliance tests for patient-api\app.py:68
    Violation: Street Address
    HIPAA Rule: §164.312(a)(1)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.312(a)(1) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.312(a)(1)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestAddressLine69:
    """
    Compliance tests for patient-api\app.py:69
    Violation: Street Address
    HIPAA Rule: §164.312(a)(1)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.312(a)(1) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.312(a)(1)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestIpLine79:
    """
    Compliance tests for patient-api\app.py:79
    Violation: IP Address
    HIPAA Rule: §164.312(e)(1)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.312(e)(1) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.312(e)(1)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )

