# Auto-generated by IBM Bob PHI Compliance Scanner
# Generated: 2026-05-17 12:48:40
# Source: audit-logger\app.py
# HIPAA Rules covered: §164.312(a)(1), §164.312(b), §164.312(d), §164.312(e)(1)

import pytest
import re

# ── Helpers ──────────────────────────────────────────────────────────────────

SSN_PATTERN    = re.compile(r'\b\d{3}-\d{2}-\d{4}\b')
MRN_PATTERN    = re.compile(r'\bMRN-?\d{4,}\b', re.IGNORECASE)
EMAIL_PATTERN  = re.compile(r'[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}')
PHONE_PATTERN  = re.compile(r'\b\d{3}[-.]\d{3}[-.]\d{4}\b')

def contains_phi(text: str) -> bool:
    """Returns True if text contains any raw PHI."""
    t = str(text)
    return bool(
        SSN_PATTERN.search(t) or
        MRN_PATTERN.search(t) or
        EMAIL_PATTERN.search(t) or
        PHONE_PATTERN.search(t)
    )

# ── Tests ─────────────────────────────────────────────────────────────────────

class TestSsnLine32:
    """
    Compliance tests for audit-logger\app.py:32
    Violation: Social Security Number
    HIPAA Rule: §164.312(a)(1)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.312(a)(1) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.312(a)(1)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestMrnLine33:
    """
    Compliance tests for audit-logger\app.py:33
    Violation: Medical Record Number
    HIPAA Rule: §164.312(a)(1)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.312(a)(1) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.312(a)(1)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestLogphiLine42:
    """
    Compliance tests for audit-logger\app.py:42
    Violation: PHI in log: Patient Name
    HIPAA Rule: §164.312(b)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.312(b) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.312(b)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestSsnLine43:
    """
    Compliance tests for audit-logger\app.py:43
    Violation: Social Security Number
    HIPAA Rule: §164.312(a)(1)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.312(a)(1) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.312(a)(1)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestMrnLine43:
    """
    Compliance tests for audit-logger\app.py:43
    Violation: Medical Record Number
    HIPAA Rule: §164.312(a)(1)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.312(a)(1) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.312(a)(1)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestSsnLine54:
    """
    Compliance tests for audit-logger\app.py:54
    Violation: Social Security Number
    HIPAA Rule: §164.312(a)(1)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.312(a)(1) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.312(a)(1)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestSsnLine55:
    """
    Compliance tests for audit-logger\app.py:55
    Violation: Social Security Number
    HIPAA Rule: §164.312(a)(1)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.312(a)(1) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.312(a)(1)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestSsnLine58:
    """
    Compliance tests for audit-logger\app.py:58
    Violation: Social Security Number
    HIPAA Rule: §164.312(a)(1)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.312(a)(1) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.312(a)(1)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestSsnLine59:
    """
    Compliance tests for audit-logger\app.py:59
    Violation: Social Security Number
    HIPAA Rule: §164.312(a)(1)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.312(a)(1) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.312(a)(1)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestLogphiLine59:
    """
    Compliance tests for audit-logger\app.py:59
    Violation: PHI in log: Social Security Number
    HIPAA Rule: §164.312(b)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.312(b) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.312(b)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestMissingauthLine24:
    """
    Compliance tests for audit-logger\app.py:24
    Violation: Endpoint missing authentication
    HIPAA Rule: §164.312(d)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.312(d) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.312(d)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestNameLine31:
    """
    Compliance tests for audit-logger\app.py:31
    Violation: Patient Name
    HIPAA Rule: §164.312(a)(1)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.312(a)(1) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.312(a)(1)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestNameLine42:
    """
    Compliance tests for audit-logger\app.py:42
    Violation: Patient Name
    HIPAA Rule: §164.312(a)(1)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.312(a)(1) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.312(a)(1)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestMissingauthLine48:
    """
    Compliance tests for audit-logger\app.py:48
    Violation: Endpoint missing authentication
    HIPAA Rule: §164.312(d)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.312(d) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.312(d)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestMissingauthLine54:
    """
    Compliance tests for audit-logger\app.py:54
    Violation: Endpoint missing authentication
    HIPAA Rule: §164.312(d)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.312(d) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.312(d)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestMissingauthLine62:
    """
    Compliance tests for audit-logger\app.py:62
    Violation: Endpoint missing authentication
    HIPAA Rule: §164.312(d)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.312(d) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.312(d)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestIpLine36:
    """
    Compliance tests for audit-logger\app.py:36
    Violation: IP Address
    HIPAA Rule: §164.312(e)(1)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.312(e)(1) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.312(e)(1)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestIpLine44:
    """
    Compliance tests for audit-logger\app.py:44
    Violation: IP Address
    HIPAA Rule: §164.312(e)(1)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.312(e)(1) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.312(e)(1)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestIpLine77:
    """
    Compliance tests for audit-logger\app.py:77
    Violation: IP Address
    HIPAA Rule: §164.312(e)(1)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.312(e)(1) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.312(e)(1)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )

