# Auto-generated by IBM Bob PHI Compliance Scanner
# Generated: 2026-05-17 12:48:40
# Source: README.md
# HIPAA Rules covered: §164.312(a)(1)

import pytest
import re

# ── Helpers ──────────────────────────────────────────────────────────────────

SSN_PATTERN    = re.compile(r'\b\d{3}-\d{2}-\d{4}\b')
MRN_PATTERN    = re.compile(r'\bMRN-?\d{4,}\b', re.IGNORECASE)
EMAIL_PATTERN  = re.compile(r'[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}')
PHONE_PATTERN  = re.compile(r'\b\d{3}[-.]\d{3}[-.]\d{4}\b')

def contains_phi(text: str) -> bool:
    """Returns True if text contains any raw PHI."""
    t = str(text)
    return bool(
        SSN_PATTERN.search(t) or
        MRN_PATTERN.search(t) or
        EMAIL_PATTERN.search(t) or
        PHONE_PATTERN.search(t)
    )

# ── Tests ─────────────────────────────────────────────────────────────────────

class TestSsnLine20:
    """
    Compliance tests for README.md:20
    Violation: Social Security Number
    HIPAA Rule: §164.312(a)(1)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.312(a)(1) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.312(a)(1)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestSsnLine25:
    """
    Compliance tests for README.md:25
    Violation: Social Security Number
    HIPAA Rule: §164.312(a)(1)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.312(a)(1) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.312(a)(1)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestSsnLine26:
    """
    Compliance tests for README.md:26
    Violation: Social Security Number
    HIPAA Rule: §164.312(a)(1)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.312(a)(1) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.312(a)(1)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )


class TestSsnLine27:
    """
    Compliance tests for README.md:27
    Violation: Social Security Number
    HIPAA Rule: §164.312(a)(1)
    """

    def test_phi_not_exposed_in_response(self, ):
        """
        §164.312(a)(1) — PHI must not appear in raw form in API responses.
        """
        # TODO: call the patched function and capture its output
        response_text = ""  # replace with actual call
        assert not contains_phi(response_text), (
            "Raw PHI found in response — violates §164.312(a)(1)"
        )

    def test_phi_redacted_in_logs(self, caplog, ):
        """
        §164.312(b) — PHI must be redacted in all log output.
        """
        import logging
        with caplog.at_level(logging.INFO):
            pass  # TODO: trigger the function that logs
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )

    def test_access_control_enforced(self, ):
        """
        §164.312(d) — Unauthenticated requests must return 401/403.
        """
        # TODO: make unauthenticated request to the endpoint
        status_code = 403  # replace with actual call
        assert status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {status_code}"
        )

    def test_audit_log_created_on_access(self, ):
        """
        §164.312(b) — Every PHI access must create an audit log entry.
        """
        # TODO: access PHI and check audit log was written
        audit_entries_before = 0  # replace with actual count
        # trigger PHI access here
        audit_entries_after = 0   # replace with actual count
        assert audit_entries_after > audit_entries_before, (
            "No audit log entry created on PHI access — violates §164.312(b)"
        )

