# Auto-generated by IBM Bob PHI Compliance Scanner
# Generated: 2026-05-17 19:53:02
# Source: audit-logger\app.py
# HIPAA Rules covered: §164.312(a)(1), §164.312(b), §164.312(d)

import pytest
import re


@pytest.fixture
def client():
    """Flask test client for audit-logger"""
    import sys
    import os
    sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '../../ehr-demo/audit-logger')))
    from app import app, audit_events
    app.config['TESTING'] = True
    audit_events.clear()
    with app.test_client() as client:
        yield client


# ── Helpers ──────────────────────────────────────────────────────────────────

SSN_PATTERN    = re.compile(r'\b\d{3}-\d{2}-\d{4}\b')
MRN_PATTERN    = re.compile(r'\bMRN-?\d{4,}\b', re.IGNORECASE)
EMAIL_PATTERN  = re.compile(r'[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}')
PHONE_PATTERN  = re.compile(r'\b\d{3}[-.]\d{3}[-.]\d{4}\b')

def contains_phi(text: str) -> bool:
    """Returns True if text contains any raw PHI."""
    t = str(text)
    return bool(
        SSN_PATTERN.search(t) or
        MRN_PATTERN.search(t) or
        EMAIL_PATTERN.search(t) or
        PHONE_PATTERN.search(t)
    )

# ── Tests ─────────────────────────────────────────────────────────────────────

class TestAudit_Logger_App_Py:
    """
    PHI Compliance tests for audit-logger\app.py
    Generated from scanner violations
    """

    def test_log_redaction_line_53(self, caplog):
        """
        §164.312(b) — PHI must be redacted in logs
        Violation at audit-logger\app.py:53
        """
        import logging
        with caplog.at_level(logging.INFO):
            # TODO: Trigger the function that logs PHI
            # Example: client.get('/endpoint')
            pass
        
        # Verify no PHI in any log record
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )


    def test_phi_redacted_line_54(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at audit-logger\app.py:54
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_phi_redacted_line_54(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at audit-logger\app.py:54
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_phi_redacted_line_71(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at audit-logger\app.py:71
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_phi_redacted_line_72(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at audit-logger\app.py:72
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_phi_redacted_line_78(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at audit-logger\app.py:78
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_phi_redacted_line_79(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at audit-logger\app.py:79
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_log_redaction_line_79(self, caplog):
        """
        §164.312(b) — PHI must be redacted in logs
        Violation at audit-logger\app.py:79
        """
        import logging
        with caplog.at_level(logging.INFO):
            # TODO: Trigger the function that logs PHI
            # Example: client.get('/endpoint')
            pass
        
        # Verify no PHI in any log record
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )


    def test_auth_required_line_32(self, client):
        """
        §164.312(d) — Endpoint must require authentication
        Violation at audit-logger\app.py:32
        """
        # Make unauthenticated request
        response = client.get('/log')
        
        # Should return 401 Unauthorized or 403 Forbidden
        assert response.status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {response.status_code}"
        )


    def test_phi_redacted_line_41(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at audit-logger\app.py:41
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_phi_redacted_line_53(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at audit-logger\app.py:53
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_auth_required_line_59(self, client):
        """
        §164.312(d) — Endpoint must require authentication
        Violation at audit-logger\app.py:59
        """
        # Make unauthenticated request
        response = client.get('/logs')
        
        # Should return 401 Unauthorized or 403 Forbidden
        assert response.status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {response.status_code}"
        )


    def test_auth_required_line_71(self, client):
        """
        §164.312(d) — Endpoint must require authentication
        Violation at audit-logger\app.py:71
        """
        # Make unauthenticated request
        response = client.get('/logs/patient/<ssn>')
        
        # Should return 401 Unauthorized or 403 Forbidden
        assert response.status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {response.status_code}"
        )


    def test_auth_required_line_82(self, client):
        """
        §164.312(d) — Endpoint must require authentication
        Violation at audit-logger\app.py:82
        """
        # Make unauthenticated request
        response = client.get('/logs/export')
        
        # Should return 401 Unauthorized or 403 Forbidden
        assert response.status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {response.status_code}"
        )

