# Auto-generated by IBM Bob PHI Compliance Scanner
# Generated: 2026-05-17 19:53:02
# Source: shared\phi_utils.py
# HIPAA Rules covered: §164.312(a)(1), §164.312(b), §164.502(b)

import pytest
import re



# ── Helpers ──────────────────────────────────────────────────────────────────

SSN_PATTERN    = re.compile(r'\b\d{3}-\d{2}-\d{4}\b')
MRN_PATTERN    = re.compile(r'\bMRN-?\d{4,}\b', re.IGNORECASE)
EMAIL_PATTERN  = re.compile(r'[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}')
PHONE_PATTERN  = re.compile(r'\b\d{3}[-.]\d{3}[-.]\d{4}\b')

def contains_phi(text: str) -> bool:
    """Returns True if text contains any raw PHI."""
    t = str(text)
    return bool(
        SSN_PATTERN.search(t) or
        MRN_PATTERN.search(t) or
        EMAIL_PATTERN.search(t) or
        PHONE_PATTERN.search(t)
    )

# ── Tests ─────────────────────────────────────────────────────────────────────

class TestShared_Phi_Utils_Py:
    """
    PHI Compliance tests for shared\phi_utils.py
    Generated from scanner violations
    """

    def test_phi_redacted_line_12(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at shared\phi_utils.py:12
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_phi_redacted_line_14(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at shared\phi_utils.py:14
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_phi_redacted_line_17(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at shared\phi_utils.py:17
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_phi_redacted_line_19(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at shared\phi_utils.py:19
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_phi_redacted_line_35(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at shared\phi_utils.py:35
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_phi_redacted_line_37(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at shared\phi_utils.py:37
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_phi_redacted_line_40(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at shared\phi_utils.py:40
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_phi_redacted_line_41(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at shared\phi_utils.py:41
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_phi_redacted_line_42(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at shared\phi_utils.py:42
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_phi_redacted_line_49(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at shared\phi_utils.py:49
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_phi_redacted_line_51(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at shared\phi_utils.py:51
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_phi_redacted_line_52(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at shared\phi_utils.py:52
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_phi_redacted_line_55(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at shared\phi_utils.py:55
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_phi_redacted_line_57(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at shared\phi_utils.py:57
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_log_redaction_line_57(self, caplog):
        """
        §164.312(b) — PHI must be redacted in logs
        Violation at shared\phi_utils.py:57
        """
        import logging
        with caplog.at_level(logging.INFO):
            # TODO: Trigger the function that logs PHI
            # Example: client.get('/endpoint')
            pass
        
        # Verify no PHI in any log record
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )


    def test_phi_redacted_line_68(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at shared\phi_utils.py:68
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_phi_redacted_line_71(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at shared\phi_utils.py:71
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_phi_redacted_line_22(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at shared\phi_utils.py:22
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_phi_redacted_line_27(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at shared\phi_utils.py:27
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_phi_redacted_line_29(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at shared\phi_utils.py:29
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_phi_redacted_line_69(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at shared\phi_utils.py:69
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_phi_redacted_line_70(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at shared\phi_utils.py:70
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_phi_redacted_line_72(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at shared\phi_utils.py:72
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_phi_redacted_line_73(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at shared\phi_utils.py:73
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_phi_redacted_line_75(self, client):
        """
        §164.502(b) — PHI must be redacted in responses
        Violation at shared\phi_utils.py:75
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )

