# Auto-generated by IBM Bob PHI Compliance Scanner
# Generated: 2026-05-17 19:53:02
# Source: billing-service\app.py
# HIPAA Rules covered: §164.312(a)(1), §164.312(b), §164.312(d), §164.502(b)

import pytest
import re


@pytest.fixture
def client():
    """Flask test client for billing-service"""
    import sys
    import os
    sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '../../ehr-demo/billing-service')))
    from app import app
    app.config['TESTING'] = True
    with app.test_client() as client:
        yield client


# ── Helpers ──────────────────────────────────────────────────────────────────

SSN_PATTERN    = re.compile(r'\b\d{3}-\d{2}-\d{4}\b')
MRN_PATTERN    = re.compile(r'\bMRN-?\d{4,}\b', re.IGNORECASE)
EMAIL_PATTERN  = re.compile(r'[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}')
PHONE_PATTERN  = re.compile(r'\b\d{3}[-.]\d{3}[-.]\d{4}\b')

def contains_phi(text: str) -> bool:
    """Returns True if text contains any raw PHI."""
    t = str(text)
    return bool(
        SSN_PATTERN.search(t) or
        MRN_PATTERN.search(t) or
        EMAIL_PATTERN.search(t) or
        PHONE_PATTERN.search(t)
    )

# ── Tests ─────────────────────────────────────────────────────────────────────

class TestBilling_Service_App_Py:
    """
    PHI Compliance tests for billing-service\app.py
    Generated from scanner violations
    """

    def test_phi_redacted_line_58(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at billing-service\app.py:58
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_phi_redacted_line_90(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at billing-service\app.py:90
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_log_redaction_line_90(self, caplog):
        """
        §164.312(b) — PHI must be redacted in logs
        Violation at billing-service\app.py:90
        """
        import logging
        with caplog.at_level(logging.INFO):
            # TODO: Trigger the function that logs PHI
            # Example: client.get('/endpoint')
            pass
        
        # Verify no PHI in any log record
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )


    def test_phi_redacted_line_102(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at billing-service\app.py:102
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_phi_redacted_line_105(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at billing-service\app.py:105
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_log_redaction_line_105(self, caplog):
        """
        §164.312(b) — PHI must be redacted in logs
        Violation at billing-service\app.py:105
        """
        import logging
        with caplog.at_level(logging.INFO):
            # TODO: Trigger the function that logs PHI
            # Example: client.get('/endpoint')
            pass
        
        # Verify no PHI in any log record
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )


    def test_auth_required_line_42(self, client):
        """
        §164.312(d) — Endpoint must require authentication
        Violation at billing-service\app.py:42
        """
        # Make unauthenticated request
        response = client.get('/claims')
        
        # Should return 401 Unauthorized or 403 Forbidden
        assert response.status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {response.status_code}"
        )


    def test_phi_redacted_line_54(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at billing-service\app.py:54
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_phi_redacted_line_59(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at billing-service\app.py:59
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_phi_redacted_line_60(self, client):
        """
        §164.502(b) — PHI must be redacted in responses
        Violation at billing-service\app.py:60
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_auth_required_line_80(self, client):
        """
        §164.312(d) — Endpoint must require authentication
        Violation at billing-service\app.py:80
        """
        # Make unauthenticated request
        response = client.get('/claims/<claim_id>')
        
        # Should return 401 Unauthorized or 403 Forbidden
        assert response.status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {response.status_code}"
        )


    def test_phi_redacted_line_90(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at billing-service\app.py:90
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_auth_required_line_94(self, client):
        """
        §164.312(d) — Endpoint must require authentication
        Violation at billing-service\app.py:94
        """
        # Make unauthenticated request
        response = client.get('/claims/patient/<int:patient_id>')
        
        # Should return 401 Unauthorized or 403 Forbidden
        assert response.status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {response.status_code}"
        )

