# Auto-generated by IBM Bob PHI Compliance Scanner
# Generated: 2026-05-17 19:53:02
# Source: patient-api\app.py
# HIPAA Rules covered: §164.312(a)(1), §164.312(b), §164.312(d), §164.502(b)

import pytest
import re


@pytest.fixture
def client():
    """Flask test client for patient-api"""
    import sys
    import os
    sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '../../ehr-demo/patient-api')))
    from app import app, init_db
    app.config['TESTING'] = True
    app.config['DATABASE'] = ':memory:'
    init_db()
    with app.test_client() as client:
        yield client


# ── Helpers ──────────────────────────────────────────────────────────────────

SSN_PATTERN    = re.compile(r'\b\d{3}-\d{2}-\d{4}\b')
MRN_PATTERN    = re.compile(r'\bMRN-?\d{4,}\b', re.IGNORECASE)
EMAIL_PATTERN  = re.compile(r'[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}')
PHONE_PATTERN  = re.compile(r'\b\d{3}[-.]\d{3}[-.]\d{4}\b')

def contains_phi(text: str) -> bool:
    """Returns True if text contains any raw PHI."""
    t = str(text)
    return bool(
        SSN_PATTERN.search(t) or
        MRN_PATTERN.search(t) or
        EMAIL_PATTERN.search(t) or
        PHONE_PATTERN.search(t)
    )

# ── Tests ─────────────────────────────────────────────────────────────────────

class TestPatient_Api_App_Py:
    """
    PHI Compliance tests for patient-api\app.py
    Generated from scanner violations
    """

    def test_phi_redacted_line_34(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at patient-api\app.py:34
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_phi_redacted_line_36(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at patient-api\app.py:36
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_phi_redacted_line_46(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at patient-api\app.py:46
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_phi_redacted_line_46(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at patient-api\app.py:46
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_phi_redacted_line_47(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at patient-api\app.py:47
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_phi_redacted_line_47(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at patient-api\app.py:47
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_phi_redacted_line_75(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at patient-api\app.py:75
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_log_redaction_line_75(self, caplog):
        """
        §164.312(b) — PHI must be redacted in logs
        Violation at patient-api\app.py:75
        """
        import logging
        with caplog.at_level(logging.INFO):
            # TODO: Trigger the function that logs PHI
            # Example: client.get('/endpoint')
            pass
        
        # Verify no PHI in any log record
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )


    def test_phi_redacted_line_85(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at patient-api\app.py:85
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_phi_redacted_line_85(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at patient-api\app.py:85
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_phi_redacted_line_86(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at patient-api\app.py:86
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_phi_redacted_line_86(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at patient-api\app.py:86
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_phi_redacted_line_91(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at patient-api\app.py:91
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_log_redaction_line_91(self, caplog):
        """
        §164.312(b) — PHI must be redacted in logs
        Violation at patient-api\app.py:91
        """
        import logging
        with caplog.at_level(logging.INFO):
            # TODO: Trigger the function that logs PHI
            # Example: client.get('/endpoint')
            pass
        
        # Verify no PHI in any log record
        for record in caplog.records:
            assert not contains_phi(record.message), (
                f"Raw PHI found in log: {record.message}"
            )


    def test_phi_redacted_line_92(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at patient-api\app.py:92
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_phi_redacted_line_33(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at patient-api\app.py:33
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_phi_redacted_line_35(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at patient-api\app.py:35
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_phi_redacted_line_37(self, client):
        """
        §164.502(b) — PHI must be redacted in responses
        Violation at patient-api\app.py:37
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_phi_redacted_line_38(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at patient-api\app.py:38
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_phi_redacted_line_39(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at patient-api\app.py:39
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_phi_redacted_line_46(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at patient-api\app.py:46
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_phi_redacted_line_46(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at patient-api\app.py:46
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_phi_redacted_line_46(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at patient-api\app.py:46
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_phi_redacted_line_46(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at patient-api\app.py:46
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_phi_redacted_line_46(self, client):
        """
        §164.502(b) — PHI must be redacted in responses
        Violation at patient-api\app.py:46
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_phi_redacted_line_47(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at patient-api\app.py:47
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_phi_redacted_line_47(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at patient-api\app.py:47
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_auth_required_line_54(self, client):
        """
        §164.312(d) — Endpoint must require authentication
        Violation at patient-api\app.py:54
        """
        # Make unauthenticated request
        response = client.get('/patients')
        
        # Should return 401 Unauthorized or 403 Forbidden
        assert response.status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {response.status_code}"
        )


    def test_auth_required_line_65(self, client):
        """
        §164.312(d) — Endpoint must require authentication
        Violation at patient-api\app.py:65
        """
        # Make unauthenticated request
        response = client.get('/patients/<int:patient_id>')
        
        # Should return 401 Unauthorized or 403 Forbidden
        assert response.status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {response.status_code}"
        )


    def test_phi_redacted_line_75(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at patient-api\app.py:75
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_auth_required_line_78(self, client):
        """
        §164.312(d) — Endpoint must require authentication
        Violation at patient-api\app.py:78
        """
        # Make unauthenticated request
        response = client.get('/patients')
        
        # Should return 401 Unauthorized or 403 Forbidden
        assert response.status_code in (401, 403), (
            f"Expected 401/403 for unauthenticated request, got {response.status_code}"
        )


    def test_phi_redacted_line_85(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at patient-api\app.py:85
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_phi_redacted_line_85(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at patient-api\app.py:85
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_phi_redacted_line_85(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at patient-api\app.py:85
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_phi_redacted_line_85(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at patient-api\app.py:85
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_phi_redacted_line_85(self, client):
        """
        §164.502(b) — PHI must be redacted in responses
        Violation at patient-api\app.py:85
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_phi_redacted_line_86(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at patient-api\app.py:86
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_phi_redacted_line_86(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at patient-api\app.py:86
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_phi_redacted_line_86(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at patient-api\app.py:86
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_phi_redacted_line_86(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at patient-api\app.py:86
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_phi_redacted_line_86(self, client):
        """
        §164.502(b) — PHI must be redacted in responses
        Violation at patient-api\app.py:86
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )


    def test_phi_redacted_line_91(self, client):
        """
        §164.312(a)(1) — PHI must be redacted in responses
        Violation at patient-api\app.py:91
        """
        # TODO: Make request that returns PHI
        response = client.get('/endpoint')
        data = response.get_json() if response.content_type == 'application/json' else response.data
        
        # Verify no raw PHI in response
        assert not contains_phi(str(data)), (
            "Raw PHI found in response — must be redacted or encrypted"
        )

